language: node_js

before_install:    
    - npm test

install:    
    - npm install

notifications:
  email:
    recipients:
      - leandro_ugioni@hotmail.com
    on_success: always
    on_failure: always